name: release

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  YARN_ENABLE_HARDENED_MODE: 0

jobs:
  stable:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    if: github.ref == 'refs/heads/master'
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@v1
    with:
      releaseScript: release
      versionScript: 'changeset-version'
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
